name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"
          enable-cache: true
          python-version: "3.10"

      - name: Lock and Sync Dependencies
        run: |
          uv lock
          uv sync --all-groups

      - name: Build Distribution
        run: |
          uv build

      - name: Publish to PyPI
        run: |
          uv publish